<a href="https://colab.research.google.com/github/abeer7asan/AI/blob/main/graduate_school_admissions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
def sigmoid(x):
  return 1/(1+np.exp(x))

In [3]:
df = pd.read_csv("/content/drive/MyDrive/AI/Exercise /graduate school admissions/binary_model.csv")

In [4]:
print(df)

     admit  gre   gpa  rank
0        0  380  3.61     3
1        1  660  3.67     3
2        1  800  4.00     1
3        1  640  3.19     4
4        0  520  2.93     4
..     ...  ...   ...   ...
344      0  520  3.35     3
345      0  500  3.03     3
346      0  600  3.35     2
347      0  580  3.80     2
348      0  400  3.36     2

[349 rows x 4 columns]


In [5]:
one_hot_encoding = pd.get_dummies(df['rank'], dtype=int)

In [6]:
print(one_hot_encoding)

     1  2  3  4
0    0  0  1  0
1    0  0  1  0
2    1  0  0  0
3    0  0  0  1
4    0  0  0  1
..  .. .. .. ..
344  0  0  1  0
345  0  0  1  0
346  0  1  0  0
347  0  1  0  0
348  0  1  0  0

[349 rows x 4 columns]


In [7]:
df_encoded = pd.concat([df, one_hot_encoding], axis=1)

In [8]:
print(df_encoded)

     admit  gre   gpa  rank  1  2  3  4
0        0  380  3.61     3  0  0  1  0
1        1  660  3.67     3  0  0  1  0
2        1  800  4.00     1  1  0  0  0
3        1  640  3.19     4  0  0  0  1
4        0  520  2.93     4  0  0  0  1
..     ...  ...   ...   ... .. .. .. ..
344      0  520  3.35     3  0  0  1  0
345      0  500  3.03     3  0  0  1  0
346      0  600  3.35     2  0  1  0  0
347      0  580  3.80     2  0  1  0  0
348      0  400  3.36     2  0  1  0  0

[349 rows x 8 columns]


In [9]:
df_encoded.drop(columns=['rank'], inplace=True)

In [10]:
print(df_encoded)

     admit  gre   gpa  1  2  3  4
0        0  380  3.61  0  0  1  0
1        1  660  3.67  0  0  1  0
2        1  800  4.00  1  0  0  0
3        1  640  3.19  0  0  0  1
4        0  520  2.93  0  0  0  1
..     ...  ...   ... .. .. .. ..
344      0  520  3.35  0  0  1  0
345      0  500  3.03  0  0  1  0
346      0  600  3.35  0  1  0  0
347      0  580  3.80  0  1  0  0
348      0  400  3.36  0  1  0  0

[349 rows x 7 columns]


In [11]:
df_encoded = df_encoded.rename(columns={1:'rank_1', 2:'rank_2',3:'rank_3', 4:'rank_4'})

In [12]:
print(df_encoded)

     admit  gre   gpa  rank_1  rank_2  rank_3  rank_4
0        0  380  3.61       0       0       1       0
1        1  660  3.67       0       0       1       0
2        1  800  4.00       1       0       0       0
3        1  640  3.19       0       0       0       1
4        0  520  2.93       0       0       0       1
..     ...  ...   ...     ...     ...     ...     ...
344      0  520  3.35       0       0       1       0
345      0  500  3.03       0       0       1       0
346      0  600  3.35       0       1       0       0
347      0  580  3.80       0       1       0       0
348      0  400  3.36       0       1       0       0

[349 rows x 7 columns]


In [13]:
X = df_encoded.drop('admit', axis=1)

In [14]:
print(X)

     gre   gpa  rank_1  rank_2  rank_3  rank_4
0    380  3.61       0       0       1       0
1    660  3.67       0       0       1       0
2    800  4.00       1       0       0       0
3    640  3.19       0       0       0       1
4    520  2.93       0       0       0       1
..   ...   ...     ...     ...     ...     ...
344  520  3.35       0       0       1       0
345  500  3.03       0       0       1       0
346  600  3.35       0       1       0       0
347  580  3.80       0       1       0       0
348  400  3.36       0       1       0       0

[349 rows x 6 columns]


In [15]:
y = df_encoded['admit']

In [16]:
print(y)

0      0
1      1
2      1
3      1
4      0
      ..
344    0
345    0
346    0
347    0
348    0
Name: admit, Length: 349, dtype: int64


split the data to test and train data

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)
print("X_train.shape:", X_train.shape)
print("X_test.shape:", X_test.shape)
print("y_train.shape:", y_train.shape)
print("y_test.shape:", y_test.shape)

X_train.shape: (279, 6)
X_test.shape: (70, 6)
y_train.shape: (279,)
y_test.shape: (70,)


In [19]:
# initialize the scaler
scaler = StandardScaler()

# apply to test and train data
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.fit_transform(X_test)



In [20]:
print(X_train_scaler)

[[-0.93009031  0.10522676 -0.42685289  1.31730563 -0.65074526 -0.47295265]
 [-0.39870083 -0.76819574  2.34272749 -0.75912528 -0.65074526 -0.47295265]
 [ 1.01833778  1.23222354 -0.42685289  1.31730563 -0.65074526 -0.47295265]
 ...
 [ 1.01833778  0.47150071  2.34272749 -0.75912528 -0.65074526 -0.47295265]
 [ 0.4869483   1.57032257 -0.42685289  1.31730563 -0.65074526 -0.47295265]
 [-1.81573944 -0.17652243 -0.42685289 -0.75912528 -0.65074526  2.11437656]]


In [21]:
print(X_test_scaler)

[[-0.74535599  0.56570684  2.78388218 -0.6770032  -0.74535599 -0.52223297]
 [-0.1490712  -1.59299862 -0.3592106  -0.6770032   1.34164079 -0.52223297]
 [-2.08699678 -1.15197277 -0.3592106   1.47709789 -0.74535599 -0.52223297]
 [ 1.63978318  0.4496474   2.78388218 -0.6770032  -0.74535599 -0.52223297]
 [ 0.         -1.105549   -0.3592106  -0.6770032  -0.74535599  1.91485422]
 [-0.4472136  -0.50203995 -0.3592106   1.47709789 -0.74535599 -0.52223297]
 [-2.68328157 -1.17518466 -0.3592106  -0.6770032   1.34164079 -0.52223297]
 [-0.2981424  -0.73415881 -0.3592106  -0.6770032  -0.74535599  1.91485422]
 [ 0.74535599 -0.78058259 -0.3592106  -0.6770032  -0.74535599  1.91485422]
 [ 1.63978318  0.61213061 -0.3592106   1.47709789 -0.74535599 -0.52223297]
 [ 1.04349839  1.54060608 -0.3592106  -0.6770032   1.34164079 -0.52223297]
 [ 1.04349839  1.26206344 -0.3592106  -0.6770032   1.34164079 -0.52223297]
 [-0.59628479  1.54060608 -0.3592106  -0.6770032   1.34164079 -0.52223297]
 [ 0.1490712   0.47285929

Initialize the ANN model

In [24]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

The model expects rows of data with 6 variables (the input_shape=(6,) argument).
The first hidden layer has 12 nodes and uses the relu activation function.
The second hidden layer has 8 nodes and uses the relu activation function.
The output layer has one node and uses the sigmoid activation function.

In [33]:
model = Sequential()
model.add(Dense(12, input_shape=(6,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


In [34]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

**Train The Model**

In [37]:
model.fit(X_train_scaler, y_train, epochs=100, batch_size=10)

Epoch 1/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5119 - accuracy: 0.7563
Epoch 2/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5118 - accuracy: 0.7563
Epoch 3/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5118 - accuracy: 0.7563
Epoch 4/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5111 - accuracy: 0.7563
Epoch 5/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5114 - accuracy: 0.7527
Epoch 6/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5113 - accuracy: 0.7599
Epoch 7/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5117 - accuracy: 0.7563
Epoch 8/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5112 - accuracy: 0.7563
Epoch 9/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5112 - accuracy: 0.7599
Epoch 10/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5106 - accuracy: 0.7563
Epoch 11/

**Evaluate The Model**

In [38]:
loss, accuracy = model.evaluate(X_test_scaler, y_test)
print('Accuracy: %.2f' % (accuracy*100))

3/3 [==============================] - 0s 7ms/step - loss: 0.7119 - accuracy: 0.6571
Accuracy: 65.71
